### ISSUE TITLE
get unknown if nothing is configured

### ISSUE THREAD

**Issue by ggzengel** [alaskacommunications/nagios_check_drbd9#5]
I use version 0.3.

```
# ./check_drbd9.pl
DRBD OKAY: 9.0.17-1 (api:2/proto:86-114)
-
version:    9.0.17-1 (api:2/proto:86-114)
transports: (api:16):
resources:  0
-
|
```

```
# cat /proc/drbd 
version: 9.0.17-1 (api:2/proto:86-114)
GIT-hash: b9abab2dd27313922797d026542b399870bfd13e build by root@px3, 2019-06-02 20:40:41
Transports (api:16):
```

```
# /usr/sbin/drbdsetup events2 --now --statistics all && echo == no error
exists -
== no error
```

```
# /usr/sbin/drbdadm sh-resources && echo == no error
== no error
```

And no parameters are passed:

```
# ./check_drbd9.pl -V
DRBD OKAY: 9.0.17-1 (api:2/proto:86-114)
-
version:    9.0.17-1 (api:2/proto:86-114)
transports: (api:16):
resources:  0
-
|
```

**Comment by syzdek** [comment]
Is the request to have check_drbd9 return UNKNOWN if no resources are configured?

**Comment by ggzengel** [comment]
No, I just get UNKNOWN and want to get OK, because there is no error.

A category of servers are prepared to use DRBD and have the check for DRBD already, because some day somebody will use DRBD.

**Similar to check_raid:**

> --noraid=STATE
>    Return STATE if no RAID controller is found. Defaults to UNKNOWN

I always check my servers for md-devices, even they don't have some:
>Plugin Output
>No RAID configuration found

```
apply Service "Raid" {
  import "generic-service"
  
  check_command = "check_raid-zmt"
  command_endpoint = host.address

  vars.raid_noraid_state = "OK"

  assign where "LINUX" in host.groups
  ignore where "VIRT" in host.groups
}
```

**Comment by syzdek** [comment]
Please leave me an example of calling check_drbd with the output.  I ran a test and it returns OKAY if zero resources are configured:

      syzdek@sysadmin.prv.nwc$ ./check_drbd9.pl; echo $?
      DRBD OKAY: 9.0.17-1 (api:2/proto:86-114)
      -
      version:    9.0.17-1 (api:2/proto:86-114)
      transports: (api:16):
      resources:  0
      -
      |
      0
      syzdek@sysadmin.prv.nwc$ /usr/sbin/drbdsetup events2 --now --statistics all; ec
      ho $?
      exists -
      0
      syzdek@sysadmin.prv.nwc$

In order for the script to return UNKNOWN (i.e. exit code 3) if zero resources are configured, you must pass the `-0` option to the script:

      syzdek@sysadmin.prv.nwc$ ./check_drbd9.pl -0; echo $?
      DRBD OKAY: 9.0.17-1 (api:2/proto:86-114)
      -
      version:    9.0.17-1 (api:2/proto:86-114)
      transports: (api:16):
      resources:  0
      -
      |
      3
      syzdek@sysadmin.prv.nwc$

Looking through the script, without the `-0` option, UNKNOWN is only returned if:
* the DRBD module is not loaded
* `drbdadm sh-resources` returns an error
* resources have special characters in their names
* `drbdsetup events2 --now --statistics all` returns an error

I could make the DRBD module return OKAY instead of UNKNOWN unless the `-0` option is provided. For the other enumerated situations, the script should return UNKNOWN or possibly CRIT since the script does not know if there is a problem or not due to the utilities exiting with errors.

**Comment by syzdek** [comment]
I've updated check_drbd9.pl to return OKAY if the DRBD module is not loaded unless the `-0` option is specified (see 391e3e4b082abdd5ecb82307a54b951836bb5699).  I also added the ability to convert UNKNOWN exit codes to CRIT (see ae6e58f8fde176062dbe81e6fb845cab958b27c5).  Does this resolve you issue?

**Comment by ggzengel** [comment]
Now it shows OK.
Thank you.
